/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //1 ,2 , 5
        // 0 , 4

        // 0, 1, 2, 4, 5
        System.out.println(new App().getGreeting());

    }
}
